version: "3.8"
services: 
  mysql: 
    container_name: mysql-container
    image: mysql:8
    env_file: .env
    restart: "always"
    volumes: 
      - './volume/mysql:/var/lib/mysql'
      - './src/infra/database/sql:/docker-entrypoint-initdb.d'
    ports:
      - "3306:3306"

  api:
    container_name: backend-container
    build: .
    restart: "always"
    image: happy-backend
    env_file: .env
    command: npm run start:prod
    volumes: 
      - ./dist:/usr/src/backend-happy/dist
    ports: 
      - "3333:3333"
    links: 
      - mysql